[Feature] Multiple toolbox items
editor-js/header pull request #79
Opened 2022-05-04 14:38 UTC by TatianaFomina

Adds ability to display 3 separate toolbox entries for header tool with different levels

2022-05-19 18:48 UTC, ilyamore88 approved these changes

2022-05-29 13:01 UTC, ilyamore88 approved these changes

2022-05-30 11:51 UTC, neSpecc commented on src/index.js
> + * @property {HeaderConfig} config - tool's default config overrides applied with this specific toolbox item
```suggestion
 * @property {HeaderData} data - tool's data overrides applied with this specific toolbox item
```

2022-05-31 14:52 UTC, ilyamore88 approved these changes

2022-05-31 15:25 UTC, gohabereg approved these changes

2022-11-14 18:11 UTC, closed without merging

2024-04-24 15:38 UTC, gohabereg approved these changes

2024-04-24 15:40 UTC, neSpecc requested changes

2024-04-24 15:40 UTC, neSpecc commented on src/index.js
> +    return [
levels configuration should be supported

2024-04-24 15:41 UTC, neSpecc commented
I'm not sure that we need to provide multiple toolbox items for Heading out of the box. It can mess the default UI. Questionable.

2024-04-24 15:45 UTC, ilyamore88 approved these changes